name: 'demo'
remark: 'demo'
namespace: 'def'
env:
  - name: JAVA_OPTS
    value: '-Xms128m -Xmx128m'
port: 8049
maven_package_dir: demo
configtemplate: demo/src/main/resources/application.yml
mult_pod: true
prod_only: true