apiVersion: apps/v1
kind: Namespace
metadata:
  name: dev

---

apiVersion: apps/v1
kind: Pod
metadata:
  name: demo
  namespace: dev
spec:
  containers:
  - name: demo
    image: demo:v1.0
    imagePullPolicy: Never
    ports:
      - containerPort: 8049

