apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: 192.168.88.138:180/13693360699/demo:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: mysecret
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: dev
  labels:
    app: demo
spec:
  ports:
    - port: 80
      targetPort: 8049
  selector:
    app: demo
  type: LoadBalancer

